name: Generate Manifest
on:
  pull_request:
    branches:
      - master

jobs:
  generate-manifest:
    name: Generate Manifest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: generating manifest
        env:
          FORCE_COLOR: 3
        run: |
          npx zx <<'EOF'
          const output = (await $`ls -d */`).stdout.trim();

          cd('.github');

          const final_manifest = await Promise.all(output.split('\n').map(async (dir) => {
              cd('../' + dir);
              const theme_manifest = (await $`cat manifest.json`).stdout.trim();
              return JSON.parse(theme_manifest);
          }));

          cd('..')

          await $`echo ${JSON.stringify(final_manifest, null, 2)} > manifest.json`
          EOF

      - name: push generated manifest
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          message: 'chore: update manifest.json'
          committer_name: GitHub Actions
          committer_email: actions@github.com
